# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: jtaoufik.Tiger
PackageVersion: 0.7.0
InstallerType: nullsoft
InstallerLocale: en-US
Scope: user
UpgradeBehavior: install
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/jtaoufik/tiger/releases/download/v0.7.0/Tiger-Setup-0.7.0-windows-x64.exe
    InstallerSha256: EC3089DE580995641F2FA91CD15F4503DB831CBB9DABBFDCB03FAAD4C2C0DF8B
ManifestType: installer
ManifestVersion: 1.6.0
